site_name: Beast

nav:
  - Home: README.md
  - Usage: Usage.md
  - Setup: Setup.md
  - Documentation: Documentation.md
  - Samples: SampleChallenges.md
  - APIDocs: /apiDocs
  - CmdRef: cmdref/beast.md

theme: mkdocs
